version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
volumes:
  postgres_data:
